/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.LoginPage;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class forgotpass extends javax.swing.JFrame {

    
    dbConnector dbc = new dbConnector();
    
    
    Color hover = new Color(0,0,0);
    Color leave = new Color(222,222,222);
    
    String roomnum;
    PreparedStatement pst;
    Statement st;
    ResultSet rs;
    Connection con;
    public forgotpass() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reg_email = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Cancel1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ans = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reg_email.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        reg_email.setForeground(new java.awt.Color(51, 51, 51));
        reg_email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(reg_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 220, 20));

        pass.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        pass.setForeground(new java.awt.Color(51, 51, 51));
        pass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 220, 20));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        jLabel4.setText("Email:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        jLabel6.setText("Security Question:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        jLabel7.setText("Answer:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 70, -1));

        Cancel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cancel.setContentAreaFilled(false);
        Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancel.setOpaque(true);
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelMouseExited(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 61, 28));

        Cancel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        Cancel1.setText("Save");
        Cancel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cancel1.setContentAreaFilled(false);
        Cancel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancel1.setOpaque(true);
        Cancel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Cancel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Cancel1MouseExited(evt);
            }
        });
        Cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel1ActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 61, 28));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        jLabel5.setText("Set Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        ans.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        ans.setForeground(new java.awt.Color(51, 51, 51));
        ans.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 220, 20));

        jTextField1.setEditable(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
        dispose();

    }//GEN-LAST:event_CancelMouseClicked

    private void CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseEntered
        Cancel.setBackground(hover);
        Cancel.setForeground(leave);
    }//GEN-LAST:event_CancelMouseEntered

    private void CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseExited
        Cancel.setBackground(leave);
        Cancel.setForeground(hover);
    }//GEN-LAST:event_CancelMouseExited

    private void Cancel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cancel1MouseEntered
        Cancel1.setBackground(hover);
        Cancel1.setForeground(leave);
    }//GEN-LAST:event_Cancel1MouseEntered

    private void Cancel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cancel1MouseExited
        Cancel1.setBackground(leave);
        Cancel1.setForeground(hover);
    }//GEN-LAST:event_Cancel1MouseExited

    private void Cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel1ActionPerformed
        if(jTextField1.getText().equals("")){
        JOptionPane.showMessageDialog(this,"Enter Email and Search it");   
        reg_email.requestFocus();
        }
    else if(ans.getText().equals("")){
        JOptionPane.showMessageDialog(this,"Enter vaild Answer");
        ans.requestFocus();
    }
    else if(pass.getText().equals("")){
        JOptionPane.showMessageDialog(this," Don't leave password empty");
        pass.requestFocus();
    }
    else{
        try { 
            rs = dbc.getData("SELECT* FROM tbl_login where log_email='"+reg_email.getText()+"' and log_sqAns='"+ans.getText()+"' ");
            
            if(rs.next()){
                dbc.updateData("UPDATE tbl_login SET log_pass= '"+pass.getText()+"' WHERE log_email='"+reg_email.getText()+"' ");
                JOptionPane.showMessageDialog(this, "Password Reset\nLogin Now","Success",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }else{
                JOptionPane.showMessageDialog( null, "Wrong Answer.", "Try Again", JOptionPane.ERROR_MESSAGE);
            }
        }   catch (SQLException ex) {
                Logger.getLogger(forgotpass.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    }//GEN-LAST:event_Cancel1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try { 
            rs = dbc.getData("SELECT* FROM tbl_login where log_email='"+reg_email.getText()+"'");
            
            if(rs.next()){
                jTextField1.setText(rs.getString("log_squest"));
            }else{
                JOptionPane.showMessageDialog(this,"Email doesn't exist");
                ans.setText("");
                pass.setText("");
                }
        } catch (SQLException ex) {
            Logger.getLogger(forgotpass.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Cancel1;
    public javax.swing.JTextField ans;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField pass;
    public javax.swing.JTextField reg_email;
    // End of variables declaration//GEN-END:variables
}
