/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.LoginPage;

import java.awt.Color;
import javax.swing.*;



public class registration extends javax.swing.JFrame {
    int mouseX;
    int mouseY;
   
    public String sex;
    
    dbConnector dbc = new dbConnector();
    
    Color hover = new Color(0,0,0);
    Color leave = new Color(222,222,222);
    
    public registration() {
        initComponents();
        
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        reg_squest = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        reg_pass = new javax.swing.JPasswordField();
        reg_user = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        reg_fname = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        reg_lname = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        reg_cnum = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        reg_email = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        reg_sqans = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rad_male = new javax.swing.JRadioButton();
        rad_trans = new javax.swing.JRadioButton();
        rad_female = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        jLabel1.setText("Username:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        jLabel2.setText("First Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        jLabel3.setText("Contact Number:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        jLabel4.setText("Email:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        jLabel5.setText("Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        reg_squest.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        reg_squest.setForeground(new java.awt.Color(51, 51, 51));
        reg_squest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your dream job?", "What is your first pet name?", "Best moment in your life?", "Who is your favorite person?" }));
        reg_squest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(reg_squest, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 219, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        jLabel8.setText("Last Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        jLabel6.setText("Security Question:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        jLabel7.setText("Answer:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        reg_pass.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        reg_pass.setForeground(new java.awt.Color(51, 51, 51));
        reg_pass.setText("jPasswordField1");
        reg_pass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        reg_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reg_passFocusGained(evt);
            }
        });
        jPanel1.add(reg_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 218, 10));

        reg_user.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        reg_user.setForeground(new java.awt.Color(51, 51, 51));
        reg_user.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(reg_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 218, 10));

        btn_register.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        btn_register.setText("Register");
        btn_register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_register.setContentAreaFilled(false);
        btn_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_register.setOpaque(true);
        btn_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registerMouseExited(evt);
            }
        });
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        jPanel1.add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 61, 28));

        Cancel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cancel.setContentAreaFilled(false);
        Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancel.setOpaque(true);
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelMouseExited(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 61, 28));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 220, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 220, -1));

        reg_fname.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        reg_fname.setForeground(new java.awt.Color(51, 51, 51));
        reg_fname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(reg_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 218, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 220, -1));

        reg_lname.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        reg_lname.setForeground(new java.awt.Color(51, 51, 51));
        reg_lname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(reg_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 218, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 220, -1));

        reg_cnum.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        reg_cnum.setForeground(new java.awt.Color(51, 51, 51));
        reg_cnum.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        reg_cnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                reg_cnumKeyTyped(evt);
            }
        });
        jPanel1.add(reg_cnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 218, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 220, -1));

        reg_email.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        reg_email.setForeground(new java.awt.Color(51, 51, 51));
        reg_email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(reg_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 218, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 220, -1));

        reg_sqans.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        reg_sqans.setForeground(new java.awt.Color(51, 51, 51));
        reg_sqans.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(reg_sqans, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 218, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 220, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 1, 11)); // NOI18N
        jLabel9.setText("Sex:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("_");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 10, -1));

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("X");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 10, 20));

        buttonGroup1.add(rad_male);
        rad_male.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        rad_male.setText("Male");
        jPanel1.add(rad_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, 20));

        buttonGroup1.add(rad_trans);
        rad_trans.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        rad_trans.setText("Trans");
        jPanel1.add(rad_trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        buttonGroup1.add(rad_female);
        rad_female.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        rad_female.setText("Female");
        jPanel1.add(rad_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        setState(login.ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        dispose();
        
        
        
    }//GEN-LAST:event_jLabel11MouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         mouseX = evt.getX();
         mouseY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int coordX = evt.getXOnScreen();
       int coordY = evt.getYOnScreen();
       
        this.setLocation(coordX-mouseX, coordY-mouseY);
    }//GEN-LAST:event_formMouseDragged

    private void CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseExited
        Cancel.setBackground(leave);
        Cancel.setForeground(hover);
    }//GEN-LAST:event_CancelMouseExited

    private void CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseEntered
        Cancel.setBackground(hover);
        Cancel.setForeground(leave);
    }//GEN-LAST:event_CancelMouseEntered

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
        dispose();
        
    }//GEN-LAST:event_CancelMouseClicked

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        
        
        String user = reg_user.getText();
        String pass = reg_pass.getText();
        String fname= reg_fname.getText();
        String lname= reg_lname.getText();
       
        String cnum = reg_cnum.getText();
        String email= reg_email.getText();
        String squest= reg_squest.getSelectedItem().toString();
        String sqans= reg_sqans.getText();
        
        
            if(user.isEmpty() || pass.isEmpty() || fname.isEmpty() || lname.isEmpty() || buttonGroup1 == null || cnum.isEmpty() || email.isEmpty() || sqans.isEmpty()){
            JOptionPane.showMessageDialog( null, "Please Fill All Fields.", "Try Again", JOptionPane.ERROR_MESSAGE);
            }else{
            rad_male.setActionCommand("Male");
            rad_female.setActionCommand("Female");
            rad_trans.setActionCommand("Trans");
            
            sex  = buttonGroup1.getSelection().getActionCommand();
             
            
            int result = dbc.insertData("INSERT INTO tbl_login(log_uname, log_pass, log_fname, log_lname, log_sex, log_cnum, log_email, log_squest, log_sqAns)"
                    + "VALUES                       ('"+user+"', '"+pass+"', '"+fname+"', '"+lname+"', '"+sex+"', '"+cnum+"', '"+email+"', '"+squest+"', '"+sqans+"')");       
            if(result == 1){
                JOptionPane.showMessageDialog( null, "Successfully Registered!");
                dispose();
                }
            }    
       
         
        
        
        
    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registerMouseExited
        btn_register.setBackground(leave);
        btn_register.setForeground(hover);
    }//GEN-LAST:event_btn_registerMouseExited

    private void btn_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registerMouseEntered
        btn_register.setBackground(hover);
        btn_register.setForeground(leave);
    }//GEN-LAST:event_btn_registerMouseEntered

    private void btn_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registerMouseClicked

    }//GEN-LAST:event_btn_registerMouseClicked

    private void reg_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reg_passFocusGained
        reg_pass.setText("");
    }//GEN-LAST:event_reg_passFocusGained

    private void reg_cnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reg_cnumKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_reg_cnumKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton btn_register;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JSeparator jSeparator4;
    public javax.swing.JSeparator jSeparator5;
    public javax.swing.JSeparator jSeparator6;
    public javax.swing.JSeparator jSeparator7;
    public javax.swing.JRadioButton rad_female;
    public javax.swing.JRadioButton rad_male;
    public javax.swing.JRadioButton rad_trans;
    public javax.swing.JTextField reg_cnum;
    public javax.swing.JTextField reg_email;
    public javax.swing.JTextField reg_fname;
    public javax.swing.JTextField reg_lname;
    public javax.swing.JPasswordField reg_pass;
    public javax.swing.JTextField reg_sqans;
    public javax.swing.JComboBox<String> reg_squest;
    public javax.swing.JTextField reg_user;
    // End of variables declaration//GEN-END:variables
}
