/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI.Pages;


import UI.LoginPage.dbConnector;
import java.awt.HeadlessException;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.*;
import net.proteanit.sql.DbUtils;
import org.joda.time.Days;
import org.joda.time.LocalDate;
        
public class CheckOUT extends javax.swing.JInternalFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    int mouseX;
    int mouseY;
    dbConnector dbc = new dbConnector();
    
    public CheckOUT() {
        initComponents();
        
        displayData();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        jTable1.setDefaultEditor(Object.class, null);
    }
    
    private void displayData(){
        String avail = "Checked IN";
        try{
            rs = dbc.getData("SELECT* FROM client where stat='"+avail+"'");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.removeColumn(jTable1.getColumnModel().getColumn(13));
            
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());
        }
    }
    public int getDays() throws ParseException{
        java.util.Date date1 =  new SimpleDateFormat("yyyy-MM-dd").parse(checkIN.getText());
        java.util.Date date2 =  new SimpleDateFormat("yyyy-MM-dd").parse(checkOUT.getText());
       
       LocalDate from = LocalDate.fromDateFields(date1);
       LocalDate to = LocalDate.fromDateFields(date2);
       int days = Days.daysBetween(from, to).getDays();
       if (days==0){
           days = 1;
       }
       return days;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        rprice1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        rtotal2 = new javax.swing.JTextField();
        fullname1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        roomno1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        pend = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        paid1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        paid2 = new javax.swing.JTextField();
        tprice1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        roomno = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        checkOUT = new javax.swing.JTextField();
        govno = new javax.swing.JTextField();
        checkIN = new javax.swing.JTextField();
        tprice = new javax.swing.JTextField();
        rprice = new javax.swing.JTextField();
        paid = new javax.swing.JTextField();
        fullname = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        govtype = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        btn_refresh = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        rptotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jDialog1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jDialog1MouseDragged(evt);
            }
        });
        jDialog1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jDialog1MousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("SAVE");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 40, 20));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Room Price:");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        rprice1.setEditable(false);
        rprice1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rprice1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(rprice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 140, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Add Payment:");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        rtotal2.setEditable(false);
        rtotal2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rtotal2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(rtotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, -1));

        fullname1.setEditable(false);
        fullname1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fullname1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fullname1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(fullname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 240, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Full Name:");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 60, -1));

        roomno1.setEditable(false);
        roomno1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        roomno1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        roomno1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(roomno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 130, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Room Number:");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 100, -1));

        pend.setEditable(false);
        pend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pend.setForeground(new java.awt.Color(88, 168, 105));
        pend.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        pend.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(pend, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 100, 20));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Pending Payment:");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 100, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("Amount Paid:");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        jPanel2.add(paid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 140, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 204, 40, 30));

        paid2.setEditable(false);
        paid2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        paid2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        paid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paid2ActionPerformed(evt);
            }
        });
        jPanel2.add(paid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 140, -1));

        tprice1.setEditable(false);
        tprice1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(tprice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("/");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("Room Total:");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 850, 210));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        jLabel11.setText("Check OUT:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        jLabel14.setText("Room Number:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        jLabel15.setText("Amount Paid:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, -1, -1));

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        jLabel17.setText("Room Price:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, -1, -1));

        jLabel18.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        jLabel18.setText("Pending:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, -1, -1));

        jLabel19.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        jLabel19.setText("Gov ID:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        roomno.setEditable(false);
        roomno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        roomno.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(roomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 90, -1));

        jLabel20.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        jLabel20.setText("Check IN:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        checkOUT.setEditable(false);
        jPanel1.add(checkOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 160, -1));

        govno.setEditable(false);
        jPanel1.add(govno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 160, -1));

        checkIN.setEditable(false);
        jPanel1.add(checkIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 160, -1));

        tprice.setEditable(false);
        jPanel1.add(tprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 140, -1));

        rprice.setEditable(false);
        jPanel1.add(rprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 140, -1));

        paid.setEditable(false);
        jPanel1.add(paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 140, -1));

        fullname.setEditable(false);
        fullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 290, -1));

        jLabel23.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        jLabel23.setText("Full Name:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel5.setText("/ Check OUT");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        govtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Driver License", "Phil Health", "NBI", "Passport", "National ID", " " }));
        govtype.setEnabled(false);
        jPanel1.add(govtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 160, -1));

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Search");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, -1));

        btn_refresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh(2).png"))); // NOI18N
        btn_refresh.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_refresh.setContentAreaFilled(false);
        btn_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jPanel1.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 223, -1, -1));

        jLabel24.setFont(new java.awt.Font("Microsoft YaHei", 0, 11)); // NOI18N
        jLabel24.setText("Room Total:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        rptotal.setEditable(false);
        jPanel1.add(rptotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 140, -1));

        jButton1.setBackground(new java.awt.Color(213, 128, 34));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CHECK OUT");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 100, 40));

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int rowindex = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        roomno.setText(""+model.getValueAt(rowindex, 0));
        fullname.setText(""+model.getValueAt(rowindex, 1));
        govtype.setSelectedItem(model.getValueAt(rowindex, 4));
        govno.setText(""+model.getValueAt(rowindex, 5));
        checkIN.setText("" + model.getValueAt(rowindex, 6));
        checkOUT.setText("" + model.getValueAt(rowindex, 7));
        rprice.setText(""+model.getValueAt(rowindex, 8));
        rptotal.setText(""+model.getValueAt(rowindex, 9));
        paid.setText(""+model.getValueAt(rowindex, 10));
        tprice.setText(""+model.getValueAt(rowindex, 11));
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> model1 = new TableRowSorter<>(model);
        jTable1.setRowSorter(model1);
        model1.setRowFilter(RowFilter.regexFilter("(?i)" + jTextField1.getText()));
    }//GEN-LAST:event_jTextField1KeyReleased

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> model1 = new TableRowSorter<>(model);
        jTable1.setRowSorter(model1);
        model1.setRowFilter(null);
       
        fullname.setText("");
        
        
        govtype.setSelectedItem(0);
        govno.setText("");
        checkIN.setText("");
        checkOUT.setText("");
        rprice.setText("");
        rptotal.setText("");
        paid.setText("");
        tprice.setText("");


        

        displayData();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        
        
        
        int result = JOptionPane.showConfirmDialog(null,"Sure? Want to Save Changes?", "CONFIRMATION",
          JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
             switch (result) {
                 case JOptionPane.YES_OPTION -> {
                      int total = Integer.parseInt(pend.getText());
                      if(total>-1000){
                      paid.setText(String.valueOf(paid2.getText()));
                      tprice.setText(String.valueOf(total));
                      }else{
                           JOptionPane.showMessageDialog( null, "Illegal Amount Paid Input.");
                      }
                 }
                 case JOptionPane.NO_OPTION -> System.out.println("You Selected No");
                 case JOptionPane.CLOSED_OPTION -> System.out.println("You Closed the prompt");
                 default -> {
                 }
        
             }
        
        jDialog1.dispose();

    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
                      int pd1 = Integer.parseInt(paid1.getText());
                      int pd2 = Integer.parseInt(paid2.getText());
                      int tp = Integer.parseInt(pend.getText());
                      int totalpd = pd1+pd2;
                      int totalprice = tp - pd1;
                      
                      paid2.setText(String.valueOf(totalpd));
                      pend.setText(String.valueOf(totalprice));
           
            
            
    }//GEN-LAST:event_jLabel2MouseClicked

    private void paid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paid2ActionPerformed

    private void jDialog1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDialog1MouseDragged
        int coordX = evt.getXOnScreen();
        int coordY = evt.getYOnScreen();
        
        jDialog1.setLocation(coordX-mouseX, coordY-mouseY);
    }//GEN-LAST:event_jDialog1MouseDragged

    private void jDialog1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDialog1MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jDialog1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String fname = fullname.getText();
        if(fname.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please Select A Row.");
        }else if(!fname.isEmpty()){
            int rptot = Integer.parseInt(rptotal.getText());
            int tptot = Integer.parseInt(tprice.getText());
            
            if(tptot>0){
                    int rp = Integer.parseInt(rprice.getText());
                    int pd = Integer.parseInt(paid.getText());
                    int totalprice = rptot - pd;
   
                    fullname1.setText(fname);
                    rprice1.setText(String.valueOf(rp));
                    rtotal2.setText(String.valueOf(rptot));
                    tprice1.setText(String.valueOf(rptot));
                    paid2.setText(String.valueOf(pd));
                    pend.setText(String.valueOf(totalprice));
                    jDialog1.pack();
                    jDialog1.setVisible(true);
                    jDialog1.setAlwaysOnTop(true);
                }else{
                    String rnum = roomno.getText();
                    String avail = "Available";
                    String out = "Checked OUT";
                    int pd = Integer.parseInt(paid.getText());
                    int tp = Integer.parseInt(tprice.getText());
                    dbc.updateData("UPDATE room SET status='"+avail+"' WHERE roomnumber= '"+rnum+"' ");
                    dbc.updateData("UPDATE client SET Paid='"+pd+"', TOTAL='"+tp+"', Stat='"+out+"' WHERE roomno= '"+rnum+"' ");
                }
       }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_refresh;
    private javax.swing.JTextField checkIN;
    private javax.swing.JTextField checkOUT;
    private javax.swing.JTextField fullname;
    private javax.swing.JTextField fullname1;
    private javax.swing.JTextField govno;
    private javax.swing.JComboBox<String> govtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField paid;
    private javax.swing.JTextField paid1;
    private javax.swing.JTextField paid2;
    private javax.swing.JTextField pend;
    private javax.swing.JTextField roomno;
    private javax.swing.JTextField roomno1;
    private javax.swing.JTextField rprice;
    private javax.swing.JTextField rprice1;
    private javax.swing.JTextField rptotal;
    private javax.swing.JTextField rtotal2;
    private javax.swing.JTextField tprice;
    private javax.swing.JTextField tprice1;
    // End of variables declaration//GEN-END:variables
}
