/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI.Pages;


import javax.swing.plaf.basic.BasicInternalFrameUI;
        
public class overview extends javax.swing.JInternalFrame {

    /**
     * Creates new form overview
     */
    public overview() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_overview = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        pn_overview.setBackground(new java.awt.Color(255, 255, 255));
        pn_overview.setOpaque(true);

        jLabel11.setText("% room avail");
        pn_overview.add(jLabel11);
        jLabel11.setBounds(110, 210, 69, 16);

        jLabel12.setText("% occupied rooms");
        pn_overview.add(jLabel12);
        jLabel12.setBounds(290, 210, 99, 16);

        jLabel13.setText("Client table");
        pn_overview.add(jLabel13);
        jLabel13.setBounds(390, 390, 60, 16);

        jLabel15.setText("current number of reservation");
        pn_overview.add(jLabel15);
        jLabel15.setBounds(620, 210, 158, 16);

        jLabel16.setText("Profile Logo");
        pn_overview.add(jLabel16);
        jLabel16.setBounds(810, 70, 64, 16);

        jLabel17.setText("Welcome back, First Name");
        pn_overview.add(jLabel17);
        jLabel17.setBounds(20, 20, 141, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_overview, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_overview, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLayeredPane pn_overview;
    // End of variables declaration//GEN-END:variables
}
