
package UI.Pages;


import UI.LoginPage.dbConnector;
import UI.LoginPage.registration;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.border.LineBorder;
import javax.swing.table.*;
import net.proteanit.sql.DbUtils;
        
public class Users extends javax.swing.JInternalFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    dbConnector dbc = new dbConnector();
    
    public Users() {
        initComponents();
        
        displayData();
        
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        usersTable.setDefaultEditor(Object.class, null);
    }
    
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            rs = dbc.getData("SELECT* FROM tbl_login");
            usersTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        pn_overview = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        btn_refresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        u_pass = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        u_sqans = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        u_username = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        u_fname = new javax.swing.JTextField();
        u_lname = new javax.swing.JTextField();
        u_cnum = new javax.swing.JTextField();
        u_email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        trans = new javax.swing.JRadioButton();
        u_squest = new javax.swing.JComboBox<>();
        u_id = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        jRadioButton1.setText("jRadioButton1");

        pn_overview.setBackground(new java.awt.Color(255, 255, 255));
        pn_overview.setOpaque(true);
        pn_overview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usersTable.setAutoCreateRowSorter(true);
        usersTable.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usersTable.getTableHeader().setReorderingAllowed(false);
        usersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usersTable);
        if (usersTable.getColumnModel().getColumnCount() > 0) {
            usersTable.getColumnModel().getColumn(0).setResizable(false);
            usersTable.getColumnModel().getColumn(1).setResizable(false);
            usersTable.getColumnModel().getColumn(2).setResizable(false);
            usersTable.getColumnModel().getColumn(3).setResizable(false);
        }

        pn_overview.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 870, 260));

        btn_refresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh(2).png"))); // NOI18N
        btn_refresh.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_refresh.setContentAreaFilled(false);
        btn_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        pn_overview.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 213, -1, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabel1.setText("Security Question:");
        pn_overview.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabel2.setText("First Name:");
        pn_overview.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabel3.setText("Password:");
        pn_overview.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabel4.setText("Last Name:");
        pn_overview.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabel8.setText("Email:");
        pn_overview.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabel10.setText("Contact Number:");
        pn_overview.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabel11.setText("Sex:");
        pn_overview.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel12.setText("ID:");
        pn_overview.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabel13.setText("Answer:");
        pn_overview.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel5.setText("/ Users");
        pn_overview.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOpaque(true);
        pn_overview.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 200, -1));

        u_pass.setEditable(false);
        u_pass.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        u_pass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        u_pass.setOpaque(true);
        pn_overview.add(u_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 200, 20));
        pn_overview.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 200, -1));

        u_sqans.setEditable(false);
        u_sqans.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        u_sqans.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        u_sqans.setOpaque(true);
        pn_overview.add(u_sqans, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 200, 20));
        pn_overview.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 200, -1));

        u_username.setEditable(false);
        u_username.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        u_username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        u_username.setOpaque(true);
        pn_overview.add(u_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 200, 20));
        pn_overview.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 200, -1));
        pn_overview.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 200, 10));
        pn_overview.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 200, 10));
        pn_overview.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 200, 10));
        pn_overview.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 200, 10));
        pn_overview.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 200, 10));

        u_fname.setEditable(false);
        u_fname.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        u_fname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        u_fname.setOpaque(true);
        pn_overview.add(u_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 200, 20));

        u_lname.setEditable(false);
        u_lname.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        u_lname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        u_lname.setOpaque(true);
        pn_overview.add(u_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 200, 20));

        u_cnum.setEditable(false);
        u_cnum.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        u_cnum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        u_cnum.setOpaque(true);
        u_cnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                u_cnumKeyTyped(evt);
            }
        });
        pn_overview.add(u_cnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 200, 20));

        u_email.setEditable(false);
        u_email.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        u_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        u_email.setOpaque(true);
        pn_overview.add(u_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 200, 20));

        jButton1.setBackground(new java.awt.Color(220, 88, 96));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pn_overview.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 70, -1));

        jButton2.setBackground(new java.awt.Color(238, 162, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.setBorderPainted(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pn_overview.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 70, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("edit");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        pn_overview.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("edit");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        pn_overview.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("edit");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        pn_overview.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("edit");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        pn_overview.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("edit");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        pn_overview.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("edit");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        pn_overview.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("edit");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        pn_overview.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setText("edit");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        pn_overview.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, -1));

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("edit");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        pn_overview.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, -1, -1));

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        female.setText("Female");
        female.setEnabled(false);
        pn_overview.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        male.setText("Male");
        male.setEnabled(false);
        pn_overview.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, 20));

        buttonGroup1.add(trans);
        trans.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        trans.setText("Trans");
        trans.setEnabled(false);
        pn_overview.add(trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, -1));

        u_squest.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N
        u_squest.setForeground(new java.awt.Color(51, 51, 51));
        u_squest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your dream job?", "What is your first pet name?", "Best moment in your life?", "Who is your favorite person?" }));
        u_squest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        u_squest.setEnabled(false);
        pn_overview.add(u_squest, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 200, 20));

        u_id.setEditable(false);
        u_id.setFont(new java.awt.Font("Microsoft YaHei", 1, 13)); // NOI18N
        u_id.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pn_overview.add(u_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 60, -1));

        jLabel22.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        jLabel22.setText("Username:");
        pn_overview.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        Add.setBackground(new java.awt.Color(90, 168, 105));
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add");
        Add.setBorderPainted(false);
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        pn_overview.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 70, -1));

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Search");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        pn_overview.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_overview)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_overview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
       
        u_id.setText("");
        u_username.setText("");
        u_pass.setText("");
        u_fname.setText("");
        u_lname.setText("");
        u_cnum.setText("");
        u_email.setText("");
        u_sqans.setText("");
        
        male.setSelected(false);
        female.setSelected(false);
        trans.setSelected(false);
        
        u_username.setBorder(new LineBorder(Color.white,1));
        u_pass.setBorder(new LineBorder(Color.white,1));
        u_fname.setBorder(new LineBorder(Color.white,1));
        u_lname.setBorder(new LineBorder(Color.white,1));
        u_cnum.setBorder(new LineBorder(Color.white,1));
        u_email.setBorder(new LineBorder(Color.white,1));
        u_sqans.setBorder(new LineBorder(Color.white,1));
        
        u_username.setEditable(false);
        u_pass.setEditable(false);
        u_fname.setEditable(false);
        u_lname.setEditable(false);
        u_cnum.setEditable(false);
        u_email.setEditable(false);
        u_squest.setEnabled(false);
        u_sqans.setEditable(false);
        
         DefaultTableModel model = (DefaultTableModel) usersTable.getModel();
        TableRowSorter<DefaultTableModel> model1 = new TableRowSorter<>(model);
        usersTable.setRowSorter(model1);
        model1.setRowFilter(null);
        
        displayData();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void usersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersTableMouseClicked
        
        int rowindex = usersTable.getSelectedRow();
        TableModel model = usersTable.getModel();
        u_id.setText(""+model.getValueAt(rowindex, 0));
        u_username.setText(""+model.getValueAt(rowindex, 1));
        u_pass.setText(""+model.getValueAt(rowindex, 2));
        u_fname.setText(""+model.getValueAt(rowindex, 3));
        u_lname.setText(""+model.getValueAt(rowindex, 4));
        
        
        String u_sex = model.getValueAt(rowindex, 5).toString();
        
        if(u_sex.equals("Male")){
            male.setSelected(true);
        }
        if(u_sex.equals("Female")){
            female.setSelected(true);
        }
        if(u_sex.equals("Trans")){
            trans.setSelected(true);
        }
        
        u_cnum.setText(""+model.getValueAt(rowindex, 6));
        u_email.setText(""+model.getValueAt(rowindex, 7));
        u_squest.setSelectedItem(model.getValueAt(rowindex, 8));
        u_sqans.setText(""+model.getValueAt(rowindex, 9));
       
        
       
       
       
        
    }//GEN-LAST:event_usersTableMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        u_username.setBorder(new LineBorder(new Color(190, 190, 190),1));
        u_username.setEditable(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
       u_pass.setBorder(new LineBorder(new Color(190, 190, 190),1));
        u_pass.setEditable(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        u_fname.setBorder(new LineBorder(new Color(190, 190, 190),1));
        u_fname.setEditable(true);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        u_lname.setBorder(new LineBorder(new Color(190, 190, 190),1));
        u_lname.setEditable(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        u_cnum.setBorder(new LineBorder(new Color(190, 190, 190),1));
        u_cnum.setEditable(true);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        male.setEnabled(true);
        female.setEnabled(true);
        trans.setEnabled(true);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        u_email.setBorder(new LineBorder(new Color(190, 190, 190),1));
        u_email.setEditable(true);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        u_squest.setEnabled(true);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        u_sqans.setBorder(new LineBorder(new Color(190, 190, 190),1));
        u_sqans.setEditable(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            
            
            String user = u_username.getText();
            String pass = u_pass.getText();
            String fname= u_fname.getText();
            String lname= u_lname.getText();
            
            String cnum = u_cnum.getText();
            String email= u_email.getText();
            String squest= u_squest.getSelectedItem().toString();
            String sqans= u_sqans.getText();
            
            String rnum = u_id.getText();
            
        if(rnum.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please Select A Row.");
        }else{
            male.setActionCommand("Male");
            female.setActionCommand("Female");
            trans.setActionCommand("Trans");
            String sex  = buttonGroup1.getSelection().getActionCommand();
            dbConnector dbc = new dbConnector();
            dbc.updateData("UPDATE tbl_login SET log_uname= '"+user+"', log_pass= '"+pass+"', log_fname= '"+fname+"', log_lname= '"+lname+"', "
                    + "log_sex= '"+sex+"', log_cnum = '"+cnum+"', log_email= '"+email+"', log_squest= '"+squest+"', "
                            + "log_sqans= '"+sqans+"' WHERE log_id= '"+u_id.getText()+"' ");
        
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        u_username.setBorder(new LineBorder(Color.white,1));
        u_username.setEditable(false);
       
        u_pass.setBorder(new LineBorder(Color.white,1));
        u_pass.setEditable(false);
       
        u_fname.setBorder(new LineBorder(Color.white,1));
        u_fname.setEditable(false);
       
        u_lname.setBorder(new LineBorder(Color.white,1));
        u_lname.setEditable(false);
        
        u_cnum.setBorder(new LineBorder(Color.white,1));
        u_cnum.setEditable(false);
        
        male.setEnabled(false);
        female.setEnabled(false);
        trans.setEnabled(false);
        
        u_email.setBorder(new LineBorder(Color.white,1));
        u_email.setEditable(false);
        
        u_squest.setEnabled(false);
        
        u_sqans.setBorder(new LineBorder(Color.white,1));
        u_sqans.setEditable(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        
        registration reg = new registration();
        reg.setVisible(true);
    }//GEN-LAST:event_AddActionPerformed

    private void u_cnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_cnumKeyTyped
       char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_u_cnumKeyTyped

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        DefaultTableModel model = (DefaultTableModel) usersTable.getModel();
        TableRowSorter<DefaultTableModel> model1 = new TableRowSorter<>(model);
        usersTable.setRowSorter(model1);
        model1.setRowFilter(RowFilter.regexFilter("(?i)" + jTextField1.getText()));;
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String rnum = u_id.getText();
        if(rnum.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please Select A Row.");
        }else{  
                        try{
                         Class.forName("com.mysql.cj.jdbc.Driver");
                        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/plasabas_db", "root", "");
                        pst = con.prepareStatement("delete from tbl_login where log_id=?");
                        pst.setString(1, u_id.getText());
                        int rowsDeleted = pst.executeUpdate();
                        if(rowsDeleted > 0){
                        JOptionPane.showMessageDialog(null, "Deleted Successfully!");
                        }else{
                        System.out.println("Deletion Failed");
                        }pst.close();
                    }catch(HeadlessException | ClassNotFoundException | SQLException ex){
                        System.out.println("Error: " + ex.getMessage());
                            }
                        
        }
                    displayData();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton btn_refresh;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JRadioButton male;
    private javax.swing.JLayeredPane pn_overview;
    public javax.swing.JRadioButton trans;
    private javax.swing.JTextField u_cnum;
    private javax.swing.JTextField u_email;
    private javax.swing.JTextField u_fname;
    private javax.swing.JTextField u_id;
    private javax.swing.JTextField u_lname;
    private javax.swing.JTextField u_pass;
    private javax.swing.JTextField u_sqans;
    public javax.swing.JComboBox<String> u_squest;
    private javax.swing.JTextField u_username;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
